name: 0.7.0.$(rev:rrrr)

trigger:
- master

stages:
- stage: build_test
  displayName: 'Build + Test'
  jobs:
  - job:
    displayName: 'Build - Ubuntu'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      lfs: true
    - script: sudo ./install-deps.sh
      displayName: 'Install build dependencies'
      workingDirectory: 'scripts'
    - script: ./build-linux.sh -c -i
      displayName: 'Build'
    - script: ./build-linux.sh -t
      displayName: 'Test'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'install'
        ArtifactName: 'drop'
        publishLocation: 'Container'

  - job:
    displayName: 'Build - Windows'
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: self
      lfs: true
    - task: PowerShell@2
      displayName: 'Install build dependencies'
      inputs:
        filePath: '.\scripts\install-deps.ps1'
        arguments: '-SkipCMake' # CMake is installed on the windows-latest image
    - task: PowerShell@2
      displayName: 'Build'
      inputs:
        filePath: './build-windows.ps1'
        arguments: '-Clean'
    - task: PowerShell@2
      displayName: 'Test'
      inputs:
        filePath: './build-windows.ps1'
        arguments: '-Test'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'install'
        ArtifactName: 'drop'
        publishLocation: 'Container'